### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by karsonkalt** [learn-co-curriculum/redux-create-store-lab#17]
I saw in the solution branch that createStore does not take the correct arguments. Should be 
`let store = createStore(candyReducer)`

**Comment by graciemcguire** [comment]
Hey @karsonkalt ! I just added a [solution](https://github.com/learn-co-curriculum/redux-create-store-lab/blob/solution/src/index.js) in there, thanks for flagging this!
We appreciate you contributing to the Flatiron School curriculum!
