### ISSUE TITLE
Node -v 7.4.0

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/redux-create-store-lab#3]
@Lukeghenco @aturkewi 
Just wanted to let you guys know. I had node version 7.4.0. Which isn't compatible with these lessons. Ended up downgrading to 6.5.0 which works. I believe it was the debug that wasn't compatible.

![screen shot 2017-02-18 at 9 04 22 am](https://cloud.githubusercontent.com/assets/16408135/23094161/47e39534-f5b9-11e6-8d60-0fe3c780009d.png)

**Comment by Lukeghenco** [comment]
@enoch2k2 I would use the node LTS which is 6.95. The 7.x can have some bad errors with older packages, if they have not been updated by their owners to use the features.
