### ISSUE TITLE
Difference between curriculum and students

### ISSUE THREAD

**Issue by pickledyamsman** [learn-co-curriculum/redux-create-store-lab#4]
The file createStore.js in the student's master branch has this code:

`// solution
export default function createStore(reducer){
}`

This code is unneeded. The curriculum master branch of this file does not have this code. Making the students branch the same as master would fix this. RIght now if the second createStore is included it breaks the tests.

@aturkewi

**Comment by aturkewi** [comment]
Re-deployed to `v-000` in the Full Stack Web. Dev. With React track twice and cannot get the updates to show up on the `v-000` deploy. :(

**Comment by aturkewi** [comment]
All fixed!

**Comment by MiriamPeskowitz** [comment]
Hey, is this lab not supposed to have a start, in package.json? 

 "scripts": {
    "debug": "node-debug --hidden node_modules _mocha --watch",
    "debug-ide": "./bin/debug-ide",
    "test": "mocha -R mocha-multi --reporter-options nyan=-,json=.results.json"
  },

 That's really confusing,maybe mention it in the README, because most labs before and after can run on the browser. Thanks for considering.

**Comment by aturkewi** [comment]
Hey @MiriamPeskowitz I moved this issue over into it's own ticket #6. This closed issue was to deal with the fact that the repo on the learn-co-students org was out of sync with the master (here) on the learn-co-curriculum org. 
Thanks for raising an issue :)
