### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by kyleblee** [learn-co-curriculum/redux-create-store-lab#5]
Student gets an error when running `npm test` that 'document is not defined' if they call their createStore function and assign it to a variable (as is done in the preceding README). I'm guessing this is an issue with jsdom in index-test.js? Or perhaps you just don't intend for them to actually call the store that they create. Slightly confusing, is all.

**Comment by maxwellbenton** [comment]
Hi there,

I am having difficulty reproducing this issue, so I'm going to close it for now. We have recently updated the dependencies, tests and starter code for this lesson so it this issue should not reoccur.

Thanks for contributing! 💙
